### ISSUE TITLE
Support `no_std` environment

### ISSUE THREAD

**Issue by al8n** [volo-rs/faststr#12]
Hi, I want to switch from `smol_str` to `faststr`, but I am blocked because `faststr` does not support `no_std`.

**Comment by PureWhiteWu** [comment]
Hi, thank you for your choice and this suggestion, we will investigate how to add `no_std` support asap.

Furthermore, if you are interested, feel free to submit a pr.

**Comment by PureWhiteWu** [comment]
Hi, a new version has been published with `no_std` support.

Please have a try!
