### ISSUE TITLE
Document the memory size of `FastStr` is not `24` which is not equal to `String` and `smol::SmolStr`

### ISSUE THREAD

**Issue by al8n** [volo-rs/faststr#19]
Hi, I found that the memory size of `FastStr` is not `24`, so switching from `String` or `SmolStr` to `FastStr` may not be harmless.

So, could this crate add documentation for this?

**Comment by PureWhiteWu** [comment]
Yep, thank you for pointing this out! I think documenting this is better, are you willing to submit a pr for this?
