### ISSUE TITLE
Got `mutable key type` clippy warning when putting `FastStr` type key into a HashMap

### ISSUE THREAD

**Issue by iamazy** [volo-rs/faststr#4]
### Version
0.2.11

### Platform

macos 12.1 M1

### Description

The affected code is as follows.

![image](https://github.com/volo-rs/faststr/assets/16559960/f4470461-b3b7-4ebc-93f7-d5b262a1da5d)

when execute `cargo clippy`, it always got output

```console
warning: mutable key type
  --> helyim/src/directory/topology/volume_grow.rs:67:9
   |
67 |         let data_centers = topology.data_centers().await?;
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#mutable_key_type
   = note: `#[warn(clippy::mutable_key_type)]` on by default
```

How to avoid such warnings?

Maybe it‘s clippy’s bug.

**Comment by PureWhiteWu** [comment]
Hi, thanks for the report.
This is a false positive because `FastStr` contains `Bytes`, you can just ignore that lint.

**Comment by iamazy** [comment]
Got it, thanks!!!
